web_homepage:
    path:     /
    defaults: { _controller: WebBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: WebBundle:Auth:login }

register:
    path:     /register
    defaults: { _controller: WebBundle:Auth:register }
