web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /web

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation
